### PR TITLE
feature/115 Layout fixes

### LINKED ISSUE #115: Refactor layout to have padding

### PR DESCRIPTION
**Pull request by moetazaneta**
Resolves #115

### CODE REVIEW

File: src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export const VisualNovelPage: FC = () => {
             </div>
             <VisualNovelTabs id={id} />
           </header>
-          <div className={cls.tabContent}>
+          <div>
```
Comment (NightOfNights) [inline src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx:59]: Extra `div`? If not, let's use `Box` instead

File: src/components/Loading/Loading.tsx [hunk 2]
```diff
@@ -5,19 +5,29 @@ import { CircularProgress as theme } from '../../theme/components/external/Circu
...
   /** Is data loading. */
-  isLoading: boolean;
+  readonly isLoading: boolean;
 
   /** Children node. */
-  children?: ReactNode;
+  readonly children?: ReactNode;
+
+  /** Whether loader should take full height. */
+  readonly fullHeight?: boolean;
```
Comment (NightOfNights) [inline src/components/Loading/Loading.tsx]: Again, don't forget about adding prefixes for `boolean` props, consts, variables and etc. I think it's common sense and logically correct + you can check props of `Chakra UI` components, `Chakra UI` devs stick to such namings too 🙄

**Review by NightOfNights — APPROVED** [review]

**Review by Moltenship — APPROVED** [review]

File: src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx (hunk 1 above)
Comment (moetazaneta) [reply src/features/VisualNovel/pages/VisualNovelPage/VisualNovelPage.tsx:59]: I don't think we should mix two styling approaches here. This component styled with css, and adding `Box` would lead to inconsistency and confusion.
