### PR TITLE
fix: show publishers #68

### LINKED ISSUE #68: Fix bugs
- [ ] fix publishers in sidebar in overview tab
- [x] #71
- [x] fix multiline tags in overview tab

### PR DESCRIPTION
**Pull request by moetazaneta**

### CODE REVIEW

File: src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx [hunk 1]
```diff
@@ -1,187 +1,191 @@
...
+          .map(p => p.name))
+        .flat()));
+    }
+    return [];
+  };
+
+  const developers = fillDevelopers(releases);
+  const publishers = fillPublishers(releases, visualNovel);
+
+  console.log(publishers);
```
Comment (Moltenship) [inline src/features/VisualNovel/pages/OverviewPage/OverviewPage.tsx]: Please, remove `console.log`

**Review by Moltenship — APPROVED** [review]
